ci:
  autoupdate_commit_msg: "chore: [pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: monthly

repos:
-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    - id: black
      language_version: python3.10
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    - id: codespell
      args: ["--ignore-words=ignore-words.txt"]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        name: isort (python)
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
- repo: local
  hooks:
    - id: deploy sqlite db
      name: deploy sqlite db
      entry: just vercel
      language: system
      pass_filenames: false
- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.12.0 # Use the latest stable version
  hooks:
    - id: markdownlint-cli2
      args: [--fix] # Optional: automatically fix issues