services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ENV: development
        SITE_URL: ${SITE_URL:-http://localhost}
    ports:
      - "80:80"
    environment:
      # Development environment variables
      - SITE_URL=${SITE_URL:-http://localhost}
      - SITE_NAME=${SITE_NAME:-RyanCheley.com}
      - AUTHOR=${AUTHOR:-Ryan Cheley}
      - TIMEZONE=${TIMEZONE:-America/Los_Angeles}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    labels:
      - "coolify.managed=false"
    networks:
      - pelican-network

networks:
  pelican-network:
    driver: bridge
