name: Pelican Publish

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: deploy code
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST_UAT }}
          key: ${{ secrets.SSH_KEY_UAT }}
          username: ${{ secrets.SSH_USERNAME_UAT }}

          script: |
            rm -rf ryancheley.com
            git clone git@github.com:ryancheley/ryancheley.com.git

            source /home/ryancheley/venv/bin/activate

            pelican ryancheley.com/content -o /home/ryancheley/output