name: Pelican Publish

on:
  push:
    paths:
      - 'content/microblog/**'
  schedule:
    - cron: '13 13 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy code
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            git clone git@github.com:ryancheley/ryancheley.com.git

            source /home/ryancheley/venv/bin/activate

            cp -r ryancheley.com/* .

            pip install -r requirements.txt

            pelican content -s publishconf.py

            rm -rf ryancheley.com/
