name: Send a Tweet
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tweet-trigger
        uses: mugi111/tweet-trigger-release@v1.1
        with:
          consumer_key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer_secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          tweet_body: "Hi, this is a test!"
