name: Send a Tweet
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tweet-trigger
        uses: mugi111/tweet-trigger-release@v1.1
        with:
          tweet_body: "Hi, this is a test!"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
